### PR TITLE
chore: add reserved keywords linter

### PR DESCRIPTION
**Pull request by arbabkhalil**
## Description

TODO: Include a detailed description of the changes in the body of the PR

## Test Instructions

TODO: Include detailed instructions that explain how your reviewers can manually test this code.

## TODOs
If anything isn't yet done, list it here
- [ ] Squash before merging

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
@arbabkhalil do you still want this PR reviewed and merged? Your PR description is blank; can you please explain the context here? Is this something that all Open edX django apps are supposed to have enabled?

**Comment by e0d** [comment]
@adzuci is this valuable to get over the line?

**Comment by bmtcril** [comment]
@pwnage101 might have some context as well, I don't know if that's still a thing that we need/use/care about, but it was initially to keep people from naming tables or columns with reserved SQL names and breaking downstream processes.

**Comment by bradenmacdonald** [comment]
Closing this PR as it seems to be abandoned. We can re-open if it would still be useful.

**Pull request closed without merging**
